name: ansarimehr

nextApp:
  component: "@sls-next/serverless-component@1.17.0"
  inputs:
    bucketName: ansarimehr-serverless-data
    cloudfront:
      defaults:
        forward:
          headers: [Host]
    domain: "ansarimehr.com"
    domainType: "both"
    domainRedirects:
      www.ansarimehr.com: https://ansarimehr.com
    publicDirectoryCache:
      value: public, max-age=604800
      test: /\.(gif|jpe?g|png|txt|xml)$/i
    runtime: nodejs14.x
    memory: 512
